import {
  assertManifestSupported,
  type ManifestRoute,
  ROUTE_MANIFEST_NAME,
  ROUTE_MANIFEST_VERSION,
  type RouteManifest
} from "./manifests.js";

/** Immutable output of the typed-route module generator. */
export interface GeneratedRouteTypes {
  /** Stable TypeScript module source. */
  readonly code: string;
  /** Route IDs represented by the module, sorted lexically. */
  readonly routeIds: readonly string[];
}

const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const routeIdPattern = /^r_[a-z0-9]+$/;
const segmentKinds = new Set(["static", "dynamic", "optional", "catch-all", "optional-catch-all"]);

function generationFailure(message: string): never {
  throw new TypeError(`[NUSA-ROUTE-0001] Cannot generate typed routes: ${message}`);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function validateRoute(route: Readonly<ManifestRoute>, ids: Set<string>): void {
  if (
    route === null ||
    typeof route !== "object" ||
    typeof route.id !== "string" ||
    !routeIdPattern.test(route.id) ||
    ids.has(route.id) ||
    (route.kind !== "page" && route.kind !== "endpoint") ||
    typeof route.pattern !== "string" ||
    !route.pattern.startsWith("/") ||
    !Array.isArray(route.segments)
  ) {
    generationFailure("manifest contains an invalid or duplicate route");
  }
  ids.add(route.id);
  const names = new Set<string>();
  for (const segment of route.segments) {
    if (
      segment === null ||
      typeof segment !== "object" ||
      !segmentKinds.has(segment.kind) ||
      typeof segment.value !== "string" ||
      segment.value.length === 0
    ) {
      generationFailure(`route ${route.id} contains an invalid segment`);
    }
    if (segment.kind !== "static") {
      if (!identifierPattern.test(segment.value) || names.has(segment.value)) {
        generationFailure(`route ${route.id} contains an invalid or duplicate parameter`);
      }
      names.add(segment.value);
    }
  }
}

function parameterType(route: Readonly<ManifestRoute>): string {
  const fields = route.segments.flatMap((segment) => {
    if (segment.kind === "static") return [];
    const optional = segment.kind === "optional" || segment.kind === "optional-catch-all";
    const value =
      segment.kind === "catch-all" || segment.kind === "optional-catch-all"
        ? "readonly [string, ...string[]]"
        : "string";
    return [`readonly ${quote(segment.value)}${optional ? "?" : ""}: ${value};`];
  });
  return fields.length === 0 ? "Readonly<Record<never, never>>" : `{ ${fields.join(" ")} }`;
}

function routeRecord(route: Readonly<ManifestRoute>): string {
  const segments = route.segments
    .map((segment) => `{ kind: ${quote(segment.kind)}, value: ${quote(segment.value)} }`)
    .join(", ");
  return `  ${quote(route.id)}: [${segments}]`;
}

/**
 * Generates the deterministic typed-route module consumed by application code.
 *
 * The generated `href()` accepts a stable route ID and exactly the parameters implied by that
 * route. Every parameter is encoded as one URL segment; catch-all values must be non-empty arrays.
 * The route manifest is treated as untrusted build input and validated before source is emitted.
 */
export function generateRouteTypes(
  manifest: Readonly<RouteManifest>
): Readonly<GeneratedRouteTypes> {
  assertManifestSupported(manifest, ROUTE_MANIFEST_NAME, ROUTE_MANIFEST_VERSION);
  if (!Array.isArray(manifest.routes)) generationFailure("manifest routes must be an array");
  const ids = new Set<string>();
  for (const route of manifest.routes) validateRoute(route, ids);
  const routes = [...manifest.routes].sort((left, right) => left.id.localeCompare(right.id, "en"));
  const routeIds = Object.freeze(routes.map((route) => route.id));
  const parameterEntries = routes
    .map((route) => `  readonly ${quote(route.id)}: ${parameterType(route)};`)
    .join("\n");
  const records = routes.map(routeRecord).join(",\n");
  const code = `/* Generated by @nusajs/compiler. Do not edit. */
export type RouteId = ${routes.length === 0 ? "never" : routes.map((route) => quote(route.id)).join(" | ")};
export interface RouteParams {
${parameterEntries}
}
type ParamsFor<Id extends RouteId> = RouteParams[Id];
const routes = {
${records}
} as const;
function fail(message: string): never { throw new TypeError(\`[NUSA-ROUTE-0001] Invalid href parameters: \${message}\`); }
function own(params: object, name: string): unknown { return Object.prototype.hasOwnProperty.call(params, name) ? (params as Record<string, unknown>)[name] : undefined; }
function encode(value: unknown, name: string): string {
  if (typeof value !== "string" || value.length === 0) fail(\`\${name} must be a non-empty string\`);
  return encodeURIComponent(value);
}
/** Builds a pathname from a generated stable route ID and its exact parameter shape. */
export function href<Id extends RouteId>(id: Id, params: ParamsFor<Id>): string {
  const segments = routes[id];
  if (segments === undefined) fail("unknown route ID");
  if (params === null || typeof params !== "object" || Array.isArray(params)) fail("params must be an object");
  const expected = new Set(segments.filter((segment) => segment.kind !== "static").map((segment) => segment.value));
  for (const name of Object.keys(params)) if (!expected.has(name)) fail(\`unexpected parameter \${name}\`);
  const output: string[] = [];
  for (const segment of segments) {
    if (segment.kind === "static") { output.push(segment.value); continue; }
    const value = own(params, segment.value);
    if (segment.kind === "optional" || segment.kind === "optional-catch-all") {
      if (value === undefined) continue;
    }
    if (segment.kind === "catch-all" || segment.kind === "optional-catch-all") {
      if (!Array.isArray(value) || value.length === 0) fail(\`\${segment.value} must be a non-empty string array\`);
      output.push(...value.map((part) => encode(part, segment.value)));
      continue;
    }
    output.push(encode(value, segment.value));
  }
  return output.length === 0 ? "/" : \`/\${output.join("/")}\`;
}
`;
  return Object.freeze({ code, routeIds });
}
