import { lstat, readFile, realpath } from "node:fs/promises";
import { isAbsolute, relative, resolve, sep } from "node:path";
import ts from "typescript";
import type { Plugin } from "vite";
import { type ConfigDiagnostic, type FrameworkConfig, parseConfig } from "./config.js";
import { createRouteManifest, type RouteManifest } from "./manifests.js";
import { parseRouteGraph } from "./route-parser.js";
import { scanRouteFiles } from "./route-scanner.js";
import { generateRouteTypes } from "./route-types.js";
import {
  type CanarySecretScanOptions,
  prepareCanaries,
  scanCanarySecretArtifacts
} from "./canary-secret-scanner.js";

/** Public virtual module containing the current deterministic route manifest. */
export const ROUTE_MANIFEST_VIRTUAL_ID = "virtual:nusajs/route-manifest";
/** Public virtual module containing generated typed-route exports. */
export const TYPED_ROUTES_VIRTUAL_ID = "virtual:nusajs/typed-routes";
const resolvedPrefix = "\0nusajs:";
const resolvedManifestId = `${resolvedPrefix}route-manifest`;
const resolvedTypesId = `${resolvedPrefix}typed-routes`;

/** Options for the private NusaJS Vite integration. */
export interface NusaVitePluginOptions {
  /** Absolute application root. Defaults to Vite's resolved root. */
  readonly root?: string;
  /** Config path relative to the application root. Set to `false` to skip config discovery. */
  readonly configFile?: string | false;
  /** Route directory relative to the application root. */
  readonly routesDirectory?: string;
  /** Exact canaries to scan from final build artifacts. Omit to disable canary scanning. */
  readonly canarySecretScan?: Readonly<CanarySecretScanOptions>;
}

/** Inspectable state produced by the Vite integration. */
export interface NusaVitePluginState {
  readonly config: Readonly<FrameworkConfig>;
  readonly routeManifest: Readonly<RouteManifest>;
}

function pluginFailure(message: string): never {
  throw new TypeError(`[NUSA-CONFIG-0001] Invalid Vite integration: ${message}`);
}

function contained(root: string, candidate: string): boolean {
  const path = relative(root, candidate);
  return path === "" || (!path.startsWith(`..${sep}`) && path !== ".." && !isAbsolute(path));
}

function safePath(root: string, input: string, label: string): string {
  const candidate = resolve(root, input);
  if (!contained(root, candidate))
    pluginFailure(`${label} must remain inside the application root`);
  return candidate;
}

function diagnosticsMessage(diagnostics: readonly Readonly<ConfigDiagnostic>[]): string {
  return diagnostics
    .map(
      (item) =>
        `${item.code} ${item.path}: expected ${item.expected}, received ${item.received}; ${item.remediation}`
    )
    .join("\n");
}

async function safeExistingPath(
  root: string,
  candidate: string,
  label: string,
  expected: "directory" | "file"
): Promise<string> {
  try {
    const metadata = await lstat(candidate);
    if (metadata.isSymbolicLink()) throw new Error("link");
    if (expected === "directory" ? !metadata.isDirectory() : !metadata.isFile())
      throw new Error("wrong kind");
    const canonicalRoot = await realpath(root);
    const canonicalCandidate = await realpath(candidate);
    if (!contained(canonicalRoot, canonicalCandidate)) throw new Error("escape");
    return canonicalCandidate;
  } catch {
    pluginFailure(`${label} must be a regular ${expected} inside the application root`);
  }
}

function manifestModule(manifest: Readonly<RouteManifest>): string {
  return `/* Generated by @nusajs/compiler. */\nexport const routeManifest = Object.freeze(${JSON.stringify(manifest)});\nexport default routeManifest;\n`;
}

/**
 * Creates the private Vite bridge for NusaJS route discovery and virtual modules.
 *
 * Configuration is parsed statically and route modules are never imported or executed. The plugin
 * adds no middleware or network endpoint; development-server security remains owned by the CLI.
 */
export function createNusaVitePlugin(options: Readonly<NusaVitePluginOptions> = {}): Plugin {
  if (options === null || typeof options !== "object" || Array.isArray(options))
    pluginFailure("options must be an object");
  if (options.root !== undefined && !isAbsolute(options.root))
    pluginFailure("root must be absolute when provided");
  if (
    options.configFile !== undefined &&
    options.configFile !== false &&
    typeof options.configFile !== "string"
  )
    pluginFailure("configFile must be a string or false");
  if (options.routesDirectory !== undefined && typeof options.routesDirectory !== "string")
    pluginFailure("routesDirectory must be a string");

  const canaries =
    options.canarySecretScan === undefined ? undefined : prepareCanaries(options.canarySecretScan);

  let root = options.root;
  let outputRoot: string | undefined;
  let manifestCode = "";
  let typesCode = "";
  let state: Readonly<NusaVitePluginState> | undefined;

  async function rebuild(addWatchFile: (file: string) => void): Promise<void> {
    if (root === undefined) pluginFailure("Vite root has not been resolved");
    root = await safeExistingPath(root, root, "root", "directory");
    const routesRoot = safePath(root, options.routesDirectory ?? "src/routes", "routesDirectory");
    const configPath =
      options.configFile === false
        ? undefined
        : safePath(root, options.configFile ?? "nusa.config.ts", "configFile");
    let config: Readonly<FrameworkConfig> = Object.freeze({
      output: "server",
      securityMode: "strict",
      dynamicValues: Object.freeze([])
    });
    if (configPath !== undefined) {
      const safeConfigPath = await safeExistingPath(root, configPath, "configFile", "file");
      addWatchFile(safeConfigPath);
      let source: string;
      try {
        source = await readFile(safeConfigPath, "utf8");
      } catch {
        pluginFailure("configFile could not be read safely");
      }
      const parsed = parseConfig(source, "<config>");
      if (!parsed.valid) pluginFailure(diagnosticsMessage(parsed.diagnostics));
      config = parsed.config;
    }
    const safeRoutesRoot = await safeExistingPath(root, routesRoot, "routesDirectory", "directory");
    const files = await scanRouteFiles({ root: safeRoutesRoot });
    for (const file of files) addWatchFile(resolve(routesRoot, file.relativePath));
    const routeManifest = createRouteManifest(parseRouteGraph(files));
    manifestCode = manifestModule(routeManifest);
    typesCode = generateRouteTypes(routeManifest).code;
    state = Object.freeze({ config, routeManifest });
  }

  return {
    name: "nusajs",
    enforce: "pre",
    configResolved(config) {
      const resolvedRoot = resolve(config.root);
      if (root !== undefined && resolve(root) !== resolvedRoot)
        pluginFailure("configured root does not match Vite's resolved root");
      root = root ?? resolvedRoot;
      outputRoot = resolve(resolvedRoot, config.build.outDir);
    },
    async buildStart() {
      await rebuild((file) => this.addWatchFile(file));
    },
    resolveId(id) {
      if (id === ROUTE_MANIFEST_VIRTUAL_ID) return resolvedManifestId;
      if (id === TYPED_ROUTES_VIRTUAL_ID) return resolvedTypesId;
      return null;
    },
    load(id) {
      if (id === resolvedManifestId) return manifestCode;
      if (id === resolvedTypesId) return typesCode;
      return null;
    },
    transform(code, id) {
      if (id !== resolvedTypesId) return null;
      return {
        code: ts.transpileModule(code, {
          compilerOptions: {
            module: ts.ModuleKind.ESNext,
            target: ts.ScriptTarget.ES2022
          },
          fileName: "typed-routes.ts"
        }).outputText,
        map: null
      };
    },
    closeBundle: {
      order: "post",
      async handler() {
        if (canaries === undefined) return;
        if (outputRoot === undefined) pluginFailure("Vite output has not been resolved");
        await scanCanarySecretArtifacts(outputRoot, canaries);
      }
    },
    api: {
      getState(): Readonly<NusaVitePluginState> {
        if (state === undefined) pluginFailure("buildStart has not completed");
        return state;
      }
    }
  };
}
